# Centmin Mod Nginx dynamic module loading
# Module RPMs install drop-in files to dynamic-modules.d/
# For manually installed modules, add files to dynamic-modules.d/
# or use dynamic-modules-includes.conf
include /usr/local/nginx/conf/dynamic-modules.d/*.conf;
include /usr/local/nginx/conf/dynamic-modules-includes.conf;
