server {
            listen 80 default_server backlog=2048 reuseport;
            server_name localhost;
            root   html;

        access_log              /usr/local/nginx/logs/localhost.access.log     combined buffer=256k flush=5m;
        error_log               /usr/local/nginx/logs/localhost.error.log      error;

# limit_conn limit_per_ip 16;
# ssi  on;

        location /nginx_status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        #allow youripaddress;
        deny all;
        }

            location / {

# block common exploits, sql injections etc
#include /usr/local/nginx/conf/block.conf;

#Enables directory listings when index file not found
#autoindex  on;

#Shows file listing times as local time
#autoindex_localtime on;

            }

include /usr/local/nginx/conf/php.conf;
include /usr/local/nginx/conf/staticfiles.conf;

#include /usr/local/nginx/conf/phpstatus.conf;
include /usr/local/nginx/conf/drop.conf;
#include /usr/local/nginx/conf/errorpage.conf;
# uncomment after: dnf install nginx-module-vts
#include /usr/local/nginx/conf/vts_mainserver.conf;

       }
