MODULES+=	upstream-check

MODULE_SUMMARY_upstream_check=	3rd-party upstream health check dynamic module

MODULE_CONTRIB_DEPS_upstream-check=	nginx_upstream_check_module

include $(foreach dep,$(MODULE_CONTRIB_DEPS_upstream-check),$(CONTRIB)/src/$(dep)/version)

MODULE_VERSION_upstream_check=	$(NGINX_UPSTREAM_CHECK_MODULE_VERSION)
MODULE_RELEASE_upstream_check=	1

MODULE_VERSION_PREFIX_upstream_check=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_upstream_check=	nginx_upstream_check_module-$(NGINX_UPSTREAM_CHECK_MODULE_VERSION).tar.gz

MODULE_CONFARGS_upstream_check=	--add-dynamic-module=nginx_upstream_check_module-$(NGINX_UPSTREAM_CHECK_MODULE_VERSION)

define MODULE_POST_upstream_check
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_upstream_check) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following to /usr/local/nginx/conf/nginx.conf
and reload nginx:

    load_module modules/ngx_http_upstream_check_module.so;

Please refer to the module documentation for further details:
https://github.com/yaoweibin/nginx_upstream_check_module

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_upstream_check
